shfmt

diff --git a/catbox b/catbox
--- a/catbox
+++ b/catbox
@@ -3,22 +3,21 @@
 FILENAME="$1"
 FILE_HOST_URL="https://catbox.moe/user/api.php"
 
-
 # if filename is empty, get the filename from stdin
 if [[ -z "$FILENAME" ]]; then
-    FILENAME=$(cat)
+	FILENAME=$(cat)
 fi
 
 if [[ ! -f "$FILENAME" ]]; then
-  echo "Error: File '$FILENAME' does not exist."
-  exit 1
+	echo "Error: File '$FILENAME' does not exist."
+	exit 1
 fi
 
 MIMETYPE=$(file --mime-type -b "$FILENAME")
 
 response=$(curl -s -X POST "$FILE_HOST_URL" \
-  -F "reqtype=fileupload" \
-  -F "userhash=" \
-  -F "fileToUpload=@$FILENAME;type=$MIMETYPE")
+	-F "reqtype=fileupload" \
+	-F "userhash=" \
+	-F "fileToUpload=@$FILENAME;type=$MIMETYPE")
 
 echo "Response from server: $response"
diff --git a/noexif b/noexif
--- a/noexif
+++ b/noexif
@@ -2,8 +2,8 @@
 
 # Check if some file names are provided as an argument
 if [ "$#" -lt 1 ]; then
-    echo "Usage: $0 <files>"
-    exit 1
+	echo "Usage: $0 <files>"
+	exit 1
 fi
 
 # The files to process
@@ -11,13 +11,13 @@ file="$*"
 
 # Check if the file exists
 for file in "$@"; do
-    if [ -f "$file" ]; then
-        # Remove all EXIF data without keeping the original file
-        exiftool -all= -overwrite_original "$file"
-        echo "EXIF data removed from $file."
+	if [ -f "$file" ]; then
+		# Remove all EXIF data without keeping the original file
+		exiftool -all= -overwrite_original "$file"
+		echo "EXIF data removed from $file."
 
-    else
-        echo "Error: File $file does not exist."
-        exit 2
-    fi
+	else
+		echo "Error: File $file does not exist."
+		exit 2
+	fi
 done
diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -8,13 +8,16 @@ pushd ~/config/nixos/
 $EDITOR
 
 if git diff --quiet HEAD -- '*.nix'; then
-    echo "No changes detected, exiting."
-    popd
-    exit 0
+	echo "No changes detected, exiting."
+	popd
+	exit 0
 fi
 
-alejandra . &>/dev/null \
-  || ( alejandra . ; echo "formatting failed!" && exit 1)
+alejandra . &>/dev/null ||
+	(
+		alejandra .
+		echo "formatting failed!" && exit 1
+	)
 
 git -P diff -U0 '*.nix'
 
