Take multiple files at once

diff --git a/noexif b/noexif
--- a/noexif
+++ b/noexif
@@ -1,20 +1,23 @@
 #!/usr/bin/env bash
 
-# Check if a file name is provided as an argument
-if [ "$#" -ne 1 ]; then
-    echo "Usage: $0 <filename>"
+# Check if some file names are provided as an argument
+if [ "$#" -lt 1 ]; then
+    echo "Usage: $0 <files>"
     exit 1
 fi
 
-# The file to process
-file=$1
+# The files to process
+file="$@"
 
 # Check if the file exists
-if [ -f "$file" ]; then
-    # Remove all EXIF data without keeping the original file
-    exiftool -all= -overwrite_original "$file"
-    echo "EXIF data removed from $file."
-else
-    echo "Error: File does not exist."
-    exit 2
-fi
+for file in "$@"; do
+    if [ -f "$file" ]; then
+        # Remove all EXIF data without keeping the original file
+        exiftool -all= -overwrite_original "$file"
+        echo "EXIF data removed from $file."
+
+    else
+        echo "Error: File $file does not exist."
+        exit 2
+    fi
+done
